version: '3.8'

services:
    natural:
        image: kooldev/php:8.3
        container_name: natural
        working_dir: /natural
        restart: always
        networks:
            - internal
            - nginx_network
        volumes:
            - '.:/natural'
            - './docker/php/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        links:
            - natural-database
        depends_on:
            - natural-database
        environment:
            - PHP_EXECUTABLE_PATH=/usr/local/bin/php
    natural-nginx:
        image: nginx:alpine
        container_name: natural-nginx
        restart: always
        working_dir: /natural
        networks:
            - internal
            - nginx_network
        ports:
            - "9003:80"
        volumes:
            - .:/natural
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - natural
    natural-composer:
        image: composer:latest
        container_name: natural-composer
        working_dir: /natural
        command: update --ignore-platform-reqs
        volumes:
            - .:/natural
        restart: on-failure
        depends_on:
            - natural
    natural-database:
        image: mariadb:latest
        restart: always
        container_name: natural-database
        working_dir: /natural
        networks:
            - internal
            - nginx_network
        command: mysqld --skip-grant-tables
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=natural_peyzaj
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
        volumes:
            - .:/natural
            - ./natural-database:/var/lib/mysql
        ports:
            - '8002:3306'
    natural-redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6378}:6378'
        volumes:
            - natural-redis:/data
        networks:
            - internal
            - nginx_network
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

    natural-npm:
        image: node:20-alpine
        container_name: natural-npm
        working_dir: /natural
        volumes:
            - '.:/natural'
        depends_on:
            - natural

networks:
    nginx_network:
        external: true
    internal:
        driver: overlay
        name: 'global'
        attachable: true
volumes:
    natural-database:
        driver: local
    natural-redis:
        driver: local
